name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # 1. Tüm geçmişi kontrol et (output dalına itme için gerekli)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

    # 2. Yılanı oluştur ve otomatik olarak 'output' dalına it
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: miaralbarghouth
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          output_branch: output # Çıktıyı bu dala it
          github_token: ${{ secrets.GITHUB_TOKEN }} # İtme izni için

    # Not: Diğer 'run: git status', 'Push changes' ve 'crazy-max' adımları artık gerekli değildir.
